export const SET_FEED_LIST = 'SET_FEED_LIST';
export const FEED_DOWN_VOTE = 'FEED_DOWN_VOTE';
export const FEED_UP_VOTE = 'FEED_UP_VOTE';
export const SET_USER_VOTED_FEED_IDS = 'SET_USER_VOTED_FEED_IDS';
export const SET_USER_UNVOTED_FEED_ID = 'SET_USER_UNVOTED_FEED_ID';
